version: 2

python:
  version: 3.9
  install:
    - requirements: doc_requirements.txt
    - requirements: docs/source/requirements.txt
    - method: pip
      path: .

sphinx:
  configuration: docs/source/conf.py

submodules:
  exclude: all
