python_library(
    dependencies=[
      "//python_client:tabulate",
      "//python_client:pydantic",
      "//python_client:numpy",
      "//python_client:qubovert",
      "//python_client:icontract",
      "//python_client:python-decouple",
    ],
    sources=["*.py", "**/*.py"],
)
